// This file is currently hardcoded, but will eventually be generated by autotune

// irrelevant import so that this is treated as a module
// otherwise module augmentation won't work
import "autotune";

type MaybePromise<T> = T | Promise<T>;

declare module "autotune" {
  interface Routes {
    products: {
      ":slug/1": MaybePromise<{ params?: "slug"[] }>;
      ":slug/2": MaybePromise<{ params?: "slug"[] }>;
    };
  }

  type RoutePath = ":slug/1" | ":slug/2";
}
